#!/bin/bash

set -x

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
cd "$SCRIPT_DIR/.."

# run ruff linter
uv run --directory devspace --dev ruff check --fix ./

# run ruff formatter
uv run --directory devspace --dev ruff format ./

# run dotenv-linter linter
uv run --project devspace --dev dotenv-linter ./devspace/.env.example

# run mypy check
dev/mypy-check
